name: Linting
on: [push, pull_request]

jobs:
  prose:
    runs-on: ubuntu-latest
    steps:

    - name: Vale
      uses: errata-ai/vale-action@v1.4.2
      
      env:
        # Required
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}